[package]
name = "rnu"
version = "0.1.0"
author  = "Linuxchr linuxchr@mail.linuxchr.de"
description = "Some Network Utilities for Linux"
license= "WTFPL"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


